version: '3'

services:
  db:
    image: mozilla/tigerblood_test_db

  web:
    image: mozilla/tigerblood
    volumes:
      - ${PWD}/test/tigerblood.config.yml:/app/config.yml
    links:
      - db
    expose:
      - "8080"
    environment:
      - TIGERBLOOD_BIND_ADDR=0.0.0.0:8080
      - DEVELOPMENT=1
      - TIGERBLOOD_DSN=host=db user=tigerblood dbname=tigerblood password=mysecretpassword sslmode=disable
    command: web --config-file /app/config.yml

  test:
    image: node:8-alpine
    environment:
      - DEVELOPMENT=1
      - TIGERBLOOD_ADDR=web:8080
    links:
      - web
    volumes:
      - ${PWD}:/ip-reputation-js-client-test
    working_dir: /ip-reputation-js-client-test
    command: npm test
